AWSTemplateFormatVersion: 2010-09-09
Description: Subdominio con HTML estático en S3 usando CloudFormation

Parameters:
  DomainName:
    Type: String
    Description: Dominio raíz en Route 53
  SubDomainName:
    Type: String
    Description: Subdominio (sin el dominio raíz)
  HostedZoneId:
    Type: String
    Description: ID de la Hosted Zone de Route 53 para el dominio raíz

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${SubDomainName}.${DomainName}"
      WebsiteConfiguration:
        IndexDocument: index.html
    DeletionPolicy: Retain

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${SubDomainName}.${DomainName}/*"

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "${SubDomainName}.${DomainName}"
      Type: A
      AliasTarget:
        DNSName: !GetAtt WebsiteBucket.WebsiteDomain
        HostedZoneId: Z3AQBSTGFYJSTF  # HostedZoneId para S3 Website en us-east-1 (puede cambiar según región)

Outputs:
  WebsiteURL:
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Description: URL pública del sitio web
