AWSTemplateFormatVersion: '2010-09-09'
Description: Crear subdominio en Route 53 con hosting S3

Parameters:
  ParentDomainName:
    Type: String
  SubDomainName:
    Type: String

Resources:
  # Hosted Zone para el subdominio
  SubDomainHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Sub "${SubDomainName}.${ParentDomainName}"

  # Bucket S3 para hosting estático
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${SubDomainName}.${ParentDomainName}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false

  # Política para permitir acceso público al bucket
  PublicBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${StaticSiteBucket.Arn}/*"

  # Registro A para apuntar el subdominio al hosting S3
  SubDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref SubDomainHostedZone
      Name: !Sub "${SubDomainName}.${ParentDomainName}"
      Type: A
      AliasTarget:
        DNSName: !Sub "s3-website-us-east-1.amazonaws.com"
        HostedZoneId: Z3AQBSTGFYJSTF # HostedZone ID fijo para S3 Website en us-east-1

Outputs:
  SubDomainName:
    Value: !Sub "${SubDomainName}.${ParentDomainName}"
  BucketName:
    Value: !Ref StaticSiteBucket
  HostedZoneId:
    Value: !Ref SubDomainHostedZone
