AWSTemplateFormatVersion: "2010-09-09"
Description: "Subdominio con hosting estático en S3 apuntando al dominio principal"

Parameters:
  ParentDomainName:
    Type: String
    Description: "Nombre de dominio padre (ej: camilovalencia.click)"
  SubDomainName:
    Type: String
    Description: "Nombre del subdominio (ej: test)"
  ParentHostedZoneId:
    Type: String
    Description: ID de la Hosted Zone del dominio padre en Route 53

Resources:
  SubDomainBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${SubDomainName}.${ParentDomainName}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SubDomainBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${SubDomainName}.${ParentDomainName}/*"

  SubDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref ParentHostedZoneId
      Name: !Sub "${SubDomainName}.${ParentDomainName}"
      Type: A
      AliasTarget:
        HostedZoneId: Z3AQBSTGFYJSTF # HostedZoneId fijo de S3 website en us-east-1
        DNSName: !Sub "${SubDomainBucket}.s3-website-us-east-1.amazonaws.com"

Outputs:
  WebsiteURL:
    Value: !GetAtt SubDomainBucket.WebsiteURL
    Description: "URL del sitio web"
